### ISSUE TITLE
Stream Audio to FM Transmitter

### ISSUE THREAD

**Issue by cukabeka** [RuneAudio/RuneOS#33]
Hi,

I stumbled across this project http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter and I think it would be amazing to have this output method included in RuneOS! What do you think about this? Any chance of implementing this?

**Comment by ACXgit** [comment]
Hi, sorry but this won't fit in our schedule of development for the next months.
